services:
  - type: web
    name: pathway-intake-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://pathway-intake-backend.onrender.com/api/v1
